version: "3.7"

services:
  psql:
    image: postgres:17.2-alpine3.21
    env_file:
      - docker.env
    ports:
      - "172.17.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - psql
