"""subscribe model

Revision ID: 230243e44f7a
Revises: 5cfb5a398fd2
Create Date: 2025-01-29 21:39:31.209943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "230243e44f7a"
down_revision: Union[str, None] = "5cfb5a398fd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coursesubs",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.pk"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "course_id", "user_id", name="idx_unique_course_user"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coursesubs")
    # ### end Alembic commands ###
